language: cpp


env:

  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
     - secure: "t65xtdQ7WpWBujB04gE7Ezh9cZ/GtHFEnwJyHeZdFDLeM0YgcNg8+Iv0LQj40DCbfMLV7c0lDV9hKOqfn+OhtHzBHglaiyHwMRZREH0VoIEnK/0W1z4nDFe0z5uv0SCp1UkhsnotDTiR99OzENg525SfTEiO5n9tdlz0gDCA40M="

matrix:
    include:
#        - os: osx
#          compiler: clang
#          osx_image: xcode7.3
#          env: FAIRSOFT_VERSION=may16p1_root5
#        - os: osx
#          compiler: clang
#          osx_image: xcode7.3
#          env: FAIRSOFT_VERSION=may16p1_root6
#        - os: osx
#          compiler: clang
#          osx_image: beta-xcode6.2
#          env: FAIRSOFT_VERSION=nov15p7_root5
#        - os: osx
#          compiler: clang
#          osx_image: beta-xcode6.2
#          env: FAIRSOFT_VERSION=nov15p7_root6
        - os: linux
          compiler: gcc
          dist: trusty
          sudo: required
          env: FAIRSOFT_VERSION=may16p1_root5
#        - os: linux
#          compiler: gcc
#          dist: trusty
#          sudo: required
#          env: FAIRSOFT_VERSION=may16p1_root6


addons:
  coverity_scan:

    # GitHub project metadata
    # ** specific to your project **
    project:
      name: FairRootGroup/FairRoot
      version: dev
      description: "dev branch"

    # Where email notification of build analysis results will be sent
    notification_email: f.uhlig@gsi.de

    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: 'mkdir build && cd build && export SIMPATH=/opt/fairsoft/${FAIRSOFT_VERSION} && cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc ..'

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make -j2

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

before_install:
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        sudo apt-get update -q;
        sudo apt-get install -y cmake cmake-data g++ gcc gfortran build-essential make patch sed 
                                libx11-dev libxft-dev libxext-dev libxpm-dev libxmu-dev libglu1-mesa-dev libgl1-mesa-dev 
                                ncurses-dev libcurl4-openssl-dev curl bzip2 gzip unzip tar subversion git xutils-dev flex 
                                bison lsb-release python-dev libc6-dev-i386 libxml2-dev wget libssl-dev 
                                automake autoconf libtool;
        wget http://fairroot.gsi.de/downloads/fairsoft-${FAIRSOFT_VERSION}_1.0_amd64.deb;
        sudo dpkg -i fairsoft-${FAIRSOFT_VERSION}_1.0_amd64.deb;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        env;
        brew update;
        if test "${_system_version}" = "10.11"; then
          brew install gcc;
        fi;
        if test "${_system_version}" = "10.9"; then
          brew tap homebrew/versions;
          brew install openssl;
          brew uninstall gcc;
          brew install homebrew/versions/gcc5;
          ln -s /usr/local/bin/gfortran-5 /usr/local/bin/gfortran;
        fi;
        curl -L -O http://fairroot.gsi.de/downloads/fairsoft_${FAIRSOFT_VERSION}_osx${_system_version}.tar.bz2;
        sudo tar -xjf fairsoft_${FAIRSOFT_VERSION}_osx${_system_version}.tar.bz2 -C /;
      fi
#          ln -s /usr/local/bin/gfortran-5 /usr/local/bin/gfortran;
#          mkdir -p /usr/local/opt/gcc/lib/gcc;
#          ln -s /usr/local/Cellar/gcc5/5.4.0/lib/gcc/5 /usr/local/opt/gcc/lib/gcc/5;

install:

before_script:
    - $CXX --version
    - cmake --version
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo "export LINUX_FLAVOUR=Ubuntu14.04" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=g++;-DCMAKE_C_COMPILER=gcc\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=\${FAIRSOFT_VERSION}" >> Dart.cfg;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        echo "export LINUX_FLAVOUR=MacOSX${_system_version}" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=clang++;-DCMAKE_C_COMPILER=clang\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=\${FAIRSOFT_VERSION}" >> Dart.cfg;
      fi
    - echo "export GIT_BRANCH=\${TRAVIS_COMMIT}" >> Dart.cfg
    - echo "export SIMPATH=/opt/fairsoft/\${FAIRSOFT_VERSION}" >> Dart.cfg; 
    - echo "export BUILDDIR=/tmp/fairroot/build_fairroot_\${FAIRSOFT_VERSION}" >> Dart.cfg
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg
    - echo "export SITE=\"Travis CI\" " >> Dart.cfg
    - echo $PWD
    - cat Dart.cfg

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
        ./Dart.sh Experimental Dart.cfg;
      fi


notifications:
  email:
    recipients:
      - m.al-turany@gsi.de
      - f.uhlig@gsi.de
    on_success: always
    on_failure: always
