language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
          dist: trusty
          sudo: required
          env: FAIRSOFT_VERSION=dev_root6
        - os: osx
          compiler: clang
          osx_image: xcode8.1
          env: FAIRSOFT_VERSION=oct17

before_install:
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        sudo apt-get update -q;
        sudo apt-get install -y cmake cmake-data g++ gcc gfortran build-essential make patch sed
                                libx11-dev libxft-dev libxext-dev libxpm-dev libxmu-dev libglu1-mesa-dev libgl1-mesa-dev
                                ncurses-dev libcurl4-openssl-dev curl bzip2 gzip unzip tar subversion git xutils-dev flex
                                bison lsb-release python-dev libc6-dev-i386 libxml2-dev wget libssl-dev
                                automake autoconf libtool;
        wget http://fairroot.gsi.de/downloads/fairsoft-${FAIRSOFT_VERSION}_1.0_amd64.deb;
        sudo dpkg -i fairsoft-${FAIRSOFT_VERSION}_1.0_amd64.deb;
        export PATH=/opt/fairsoft/${FAIRSOFT_VERSION}/bin:$PATH;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        env;
        brew update;
        if test "${_system_version}" = "10.12"; then
          brew install --force-bottle gcc;
          brew link --overwrite gcc
        fi;
        curl -L -O http://fairroot.gsi.de/downloads/fairsoft_${FAIRSOFT_VERSION}_osx${_system_version}.tar.bz2;
        sudo tar -xjf fairsoft_${FAIRSOFT_VERSION}_osx${_system_version}.tar.bz2 -C /;
        export PATH=/opt/fairsoft/${FAIRSOFT_VERSION}/bin:$PATH;
      fi
#          ln -s /usr/local/bin/gfortran-5 /usr/local/bin/gfortran;
#          mkdir -p /usr/local/opt/gcc/lib/gcc;
#          ln -s /usr/local/Cellar/gcc5/5.4.0/lib/gcc/5 /usr/local/opt/gcc/lib/gcc/5;

install:

before_script:
    - $CXX --version
    - cmake --version
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo "export LINUX_FLAVOUR=Ubuntu14.04" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=g++;-DCMAKE_C_COMPILER=gcc\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=\${FAIRSOFT_VERSION}" >> Dart.cfg;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        echo "export LINUX_FLAVOUR=MacOSX${_system_version}" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=clang++;-DCMAKE_C_COMPILER=clang\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=\${FAIRSOFT_VERSION}" >> Dart.cfg;
      fi
    - if test "$TRAVIS_PULL_REQUEST" = "false"; then
        echo "export GIT_BRANCH=\${TRAVIS_COMMIT}" >> Dart.cfg;
      else
        echo "export GIT_BRANCH=PR#\${TRAVIS_PULL_REQUEST}_\${TRAVIS_PULL_REQUEST_BRANCH}" >> Dart.cfg;
      fi
    - echo "export SIMPATH=/opt/fairsoft/\${FAIRSOFT_VERSION}" >> Dart.cfg;
    - echo "export BUILDDIR=/tmp/fairroot/build_fairroot_\${FAIRSOFT_VERSION}" >> Dart.cfg
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg
    - echo "export SITE=\"Travis CI\" " >> Dart.cfg
    - echo "export PATH=$SIMPATH/bin:$PATH" >> Dart.cfg
    - echo $PWD
    - cat Dart.cfg

script:
    - ./Dart.sh Experimental Dart.cfg

notifications:

  email:
    recipients:
      - m.al-turany@gsi.de
      - f.uhlig@gsi.de
    on_success: always
    on_failure: always
